# Generated by Django 5.2.4 on 2025-07-17 15:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('header', models.CharField(blank=True, max_length=128, null=True)),
                ('ordre', models.SmallIntegerField(blank=True, null=True)),
                ('cta', models.CharField(blank=True, default='Free quote', max_length=128, null=True)),
                ('year_free_mth', models.SmallIntegerField(blank=True, default=2, null=True)),
                ('first_time_disc', models.SmallIntegerField(blank=True, default=50, null=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('custom_domain', models.BooleanField(blank=True, null=True)),
                ('mailbox', models.BooleanField(blank=True, null=True)),
                ('ecommerce', models.BooleanField(blank=True, null=True)),
                ('vitrine', models.BooleanField(blank=True, null=True)),
                ('max_users', models.SmallIntegerField(blank=True, null=True)),
                ('max_clients', models.SmallIntegerField(blank=True, null=True)),
                ('max_products', models.SmallIntegerField(blank=True, null=True)),
                ('max_pdfs', models.SmallIntegerField(blank=True, null=True)),
                ('max_excels', models.SmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'back_tab_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=32, null=True)),
                ('instance', models.CharField(blank=True, max_length=128, null=True)),
                ('operation', models.CharField(choices=[('C', 'Create'), ('R', 'Read'), ('U', 'Update'), ('D', 'Delete')], default='C', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'back_tab_registre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('date_fm', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'back_tab_subscription',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=32, null=True)),
                ('mode', models.CharField(blank=True, max_length=32, null=True)),
                ('date_made', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=16, null=True)),
                ('maker', models.CharField(blank=True, max_length=64, null=True)),
                ('note', models.CharField(blank=True, max_length=64, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'back_tab_system_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('tel', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=16, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=16, null=True)),
                ('domain', models.CharField(blank=True, max_length=32, null=True)),
                ('slug', models.CharField(blank=True, max_length=32, null=True)),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('channel', models.CharField(blank=True, max_length=32, null=True)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'back_tab_tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_superuser', models.BooleanField(blank=True, null=True)),
                ('is_admin', models.BooleanField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_on', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'back_tab_user',
                'managed': False,
            },
        ),
    ]
