# Generated by Django 5.2.4 on 2025-07-17 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0001_initial'),
    ]

    operations = [
    ]
