# Generated by Django 5.2.4 on 2025-07-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0003_auto_20250717_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registre',
            options={},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={},
        ),
        migrations.AlterModelOptions(
            name='systempayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
