# Generated by Django 5.2.4 on 2025-07-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0004_alter_plan_options_alter_registre_options_and_more'),
    ]

    operations = [
    ]
