# Generated by Django 5.2.4 on 2025-07-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250717_1606'),
    ]

    operations = [
    ]
