# Generated by Django 5.2.4 on 2025-07-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20250717_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='commande',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ensemble',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ensembleproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entree',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fabricant',
            options={},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fournisseur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={},
        ),
        migrations.AlterModelOptions(
            name='magasin',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rayon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reception',
            options={},
        ),
        migrations.AlterModelOptions(
            name='societe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sortie',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehiculemodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehiculeproduct',
            options={},
        ),
    ]
