# Generated by Django 5.2.4 on 2025-07-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_office', '0004_alter_plan_options_alter_registre_options_and_more'),
        ('base', '0004_alter_category_options_alter_categoryproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_category', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_category', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.category'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_categ_prod', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_categ_prod', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_client', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='client',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_client', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='client',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.societe'),
        ),
        migrations.AddField(
            model_name='commande',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.client'),
        ),
        migrations.AddField(
            model_name='commande',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_commande', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='commande',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_commande', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_ensemble', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='ensemble',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_ensemble', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='ensembleproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_ensemble_prod', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='ensembleproduct',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_ensemble_prod', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='ensembleproduct',
            name='ensemble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.ensemble'),
        ),
        migrations.AddField(
            model_name='ensembleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='entree',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_entree', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='entree',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_entree', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='entree',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='entree',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.rayon'),
        ),
        migrations.AddField(
            model_name='entree',
            name='reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.reception'),
        ),
        migrations.AddField(
            model_name='fabricant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_fabricant', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='fabricant',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_fabricant', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_file', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='file',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_file', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='file',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='floor',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_floor', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='floor',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_floor', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='floor',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.magasin'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_fournisseur', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_fournisseur', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='societe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.societe'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_group', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_group', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_magasin', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='magasin',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_magasin', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.commande'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_payment', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='payment',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_payment', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_product', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_product', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabricant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.fabricant'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.group'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_rayon', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_rayon', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='rayon',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.floor'),
        ),
        migrations.AddField(
            model_name='reception',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_reception', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='reception',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_reception', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='reception',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.fournisseur'),
        ),
        migrations.AddField(
            model_name='societe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_societe', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='societe',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_societe', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='commande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='sorties', to='base.commande'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_sortie', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_sortie', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='sortie',
            name='rayon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.rayon'),
        ),
        migrations.AddField(
            model_name='stock',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_stock', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='stock',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_stock', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='stock',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.magasin'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='vehiculemodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_vehicule_model', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='vehiculemodel',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_vehicule_model', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='vehiculeproduct',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='created_vehic_prod', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='vehiculeproduct',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='edited_vehic_prod', to='back_office.user'),
        ),
        migrations.AddField(
            model_name='vehiculeproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.product'),
        ),
        migrations.AddField(
            model_name='vehiculeproduct',
            name='vehicule_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='base.vehiculemodel'),
        ),
    ]
