# Generated by Django 5.2.4 on 2025-07-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_category_created_by_category_edited_by_and_more'),
    ]

    operations = [
    ]
